language: node_js
node_js:
 - "stable"
install:
 - npm install -g codecov
before_script: 
 - chmod 0777 ./node_modules/.bin/mocha
 - chmod 0777 ./node_modules/.bin/istanbul
script: 
 - istanbul cover --no-default-excludes -x "**/node_modules/**" ./node_modules/mocha/bin/_mocha --reporter lcov --R
 - codecov