matrix:
  include:
    - language: php
      php:
      - "7.1"
      - "7.2"
      - hhvm
      stages:
      - name: deploy
        if: commit_message =~ /(\[makebuild\])/
      install:
      - composer install --prefer-source --no-interaction --dev
      script:
      - phpunit test/
      - ls -l
      - pwd
      deploy:
        provider: releases
        api_key: "$GITHUB_TOKEN"
        file: desescalator.zip
      env:
        global:
          secure: "T52wMEfcgYeXNsd/MJtw4YORlDkdswYI/34M5KRAODIhyZejTTKd6gM+8tNjKhr7Xwwfy9oN3Fiaaf5kE7oH2gl1U8EQk929RtOzQ4iETpjeytUZKMg1mRauwBqO/bkP0mGvj24Aswv8SWXFe88MRXv3j5Lz6ncX37yI9CVKGB6ecOstpW7dMJEcKmMi7EhwX2uuuxxt7EepOMn0IG+3Ux+7BPNNqx3tUysdikqlmr5QMHaCc1/vwr7eRj6IPDiBujwByRyymBgToMpG0+ECMdR+Gx9shGEgPY54oCZAo8tv1j1aAXVuEIAdSjUsDcmK/O4j8bl8YHBBc4z7AGUkDxErLAJd6lY9ZeKt0YE9ynr0suh+gAXocN7VWet4zifPk/sVLLrGTa3ppWLgI8FKQNKobd5Z8oXeuXi+hvh3nfZGC+kCeDo/+3nCQA5MAd39dC2RB3G+V76jb/w0DWSebVOHE9miZKPlt/5kERrw1h4O/8V/UejFWCL36ZMnRpEojJjAQjBYuovrA/uiT3t8QL1ad2h250PMO5t4LzQVnnHGtjd3wTLfU3rDzY4ClgM3/ALCwRV80B44IMKXqxR2ZKfN5b2XdNK9Z4qXp+XNwTQbMpy5e6mQ+79ytWSW9XqQVpoLpar0iri81tbpVsFNrRxHIHXCTmeHiBG29xtzvtk="
      before_install:
      - echo $secret_pass | gpg --passphrase-fd 0 secret.php.gpg
      - mv desescalator_secret ../
      - mv secret.php ../desescalator_secret/src/
      - cd ../desescalator_secret/src/
      - pwd
      - ls
      - cd ../
      - composer install
      - cd ../desescalator/
      - pwd
    - language: node_js
      node_js:
      - "iojs"
      - "7"
      - 10.14.2
      before_script: chmod 0777 ./node_modules/.bin/mocha
      script:
      -   npm test test/
      cache:
        directories:
        - "node_modules"

