language: node_js
node_js:
 - "stable"
install:
 - npm install -g codecov
before_script: chmod 0777 ./node_modules/.bin/mocha
script: 
 - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
 - codecov