language: php
php:
- 7.1
- 7.2
- hhvm
stages:
- name: deploy
  if: commit_message =~ /(\[makebuild\])/
install:
- composer install --prefer-source --no-interaction --dev
script:
- phpunit test/
- ls -l
- pwd
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file: desescalator.zip
before_install:
- echo $secret_pass | gpg --passphrase-fd 0 secret.php.gpg
- mkdir ../desescalator_secret
- mv secret.php ../desescalator_secret/
env:
  global:
    secure: ZhVK7tIO2RyL1uAHGYY9VBbxEX0+031cvniIpymx0YuPiwx2larPULfdlGYIPrKe8/9HAGJnAeXnOQwBfUip720PDIoYPu2APMGWzq4MLIisrw3+Dz/UgCS7n1QNi5lgE4PqML+ufxjgh6ftHh23pHyDZWdHv8Mup6kEx4pQBYgf/FwbsfmzpJCqAMAYLVqg2hiMb8Y/nw48WtY8qKKEPWgpconAWSuiU9LHKj+S4vMJnMFV3MWXyDa+3goObeN0VHHkHe/eunFVkCUpLmj9TSoIgamrz/LkjaaaRKIl+b4xeqIN7gYvoPHElJCzLcU7QabZOhoCk3Ds2RlQLRTWt2zD0ppkzH1jmjH0aIj9Fb8SB++RrRBcJDkn9tEr8/bxbuI2Z0aWvrIta02Ag2pwXM3ZoKBSqQ9ZGzqmRxatOHZ97pjHTT1IFN8McCrVnIAa8V7mBwyrgu4Cczt4R9xrLdnP8x67SHsW2HjkXiLuAMEPLXALH83Kwmg7olqebK7y38yWeWTvv7NqZeSQ7OGLDXjkHbFlAa+Qm9E3rMl2MbbuoHuXGCYiLTcTIXt5mc6xwSgwGtLBurVXbPi5sb0tWUs1Sa5J4UL2eWEISgqv49+79mLqs4SKw8fEi1otw16L7+7I8ZhFpFS3thwdEQmSjvr/xekOig/iYH0fuweTgfw=
