language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - 5.4
  - 5.5
  - 5.6
  - hhvm

stages:
  - name: deploy
    if: commit_message =~ /(\[makebuild\])/

install:
  - composer install --prefer-source --no-interaction --dev


script:
  - phpunit
  - ls -l

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: desescalator.zip
  