language: node_js
node_js:
 - "stable"
before_install:
  - npm install
install:
 - npm install -g codecov
before_script: 
 - chmod 0777 ./node_modules/.bin/mocha
 - chmod 0777 ./node_modules/.bin/istanbul
 - chmod 0777 ./node_modules/.bin/eslint
script: 
 - npm run lint -s -ddd
 - istanbul cover --no-default-excludes -x "**/node_modules/**" ./node_modules/mocha/bin/_mocha --reporter test --R
 - codecov